/**
 * src/legal.js — Privacy Policy and Terms of Service pages.
 *
 * Both are served as standalone HTML (Pi Network's reviewers fetch them directly,
 * so they must render without the SPA). The platform fee is read live from
 * platform_settings so the documents never contradict what the app actually charges.
 */

const OPERATOR      = process.env.LEGAL_OPERATOR_NAME  || 'the Work Pro team';
const JURISDICTION  = process.env.LEGAL_JURISDICTION   || 'the Republic of Lithuania';
const CONTACT_EMAIL = process.env.LEGAL_CONTACT_EMAIL  || 'divashnov@gmail.com';
const LAST_UPDATED  = 'July 2026';

const STYLE = `
  :root { color-scheme: light dark; }
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:760px;
       margin:40px auto;padding:0 20px 80px;color:#1f2937;line-height:1.65;font-size:15px}
  h1{color:#6b21a8;font-size:1.7em;margin-bottom:.2em}
  h2{margin-top:2em;font-size:1.15em;color:#111827;border-bottom:1px solid #e5e7eb;padding-bottom:.3em}
  h3{margin-top:1.4em;font-size:1em;color:#374151}
  em.upd{color:#6b7280;font-size:.9em}
  ul{padding-left:1.3em} li{margin:.35em 0}
  .box{background:#fef3c7;border-left:4px solid #f59e0b;padding:12px 16px;margin:1.5em 0;border-radius:6px}
  .box strong{color:#92400e}
  code{background:#f3f4f6;padding:1px 5px;border-radius:4px;font-size:.9em}
  a{color:#6b21a8}
  @media(prefers-color-scheme:dark){
    body{background:#0f172a;color:#e2e8f0}
    h1{color:#c4b5fd} h2{color:#f1f5f9;border-color:#334155} h3{color:#cbd5e1}
    .box{background:#422006;border-color:#f59e0b} .box strong{color:#fcd34d}
    code{background:#1e293b} a{color:#c4b5fd}
  }
`;

const shell = (title, body) =>
  `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">` +
  `<meta name="viewport" content="width=device-width,initial-scale=1">` +
  `<title>Work Pro – ${title}</title><style>${STYLE}</style></head><body>${body}</body></html>`;

// ─── Privacy Policy ───────────────────────────────────────────────────────────
function privacyHtml() {
  return shell('Privacy Policy', `
<h1>Work Pro Privacy Policy</h1>
<p><em class="upd">Last updated: ${LAST_UPDATED}</em></p>

<p>Work Pro ("the App", "we", "us") is a freelance marketplace built on the Pi Network,
operated by ${OPERATOR}. This policy explains what we collect, why, and what rights you have.
It applies to every user of the App.</p>

<div class="box">
<strong>Key point:</strong> Work Pro is a neutral venue that connects clients and freelancers.
We are not a party to the contracts users form with each other, not an employer, not an agent,
and not a payment institution. Pi transactions are executed by the Pi Network, not by us.
</div>

<h2>1. Data Controller</h2>
<p>The data controller for personal data processed through the App is ${OPERATOR}.
Contact for all privacy matters: <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.</p>

<h2>2. Information We Collect</h2>
<h3>2.1 Provided by the Pi Network SDK at login</h3>
<ul>
  <li>Pi Network username and Pi user identifier (UID)</li>
  <li>An access token used solely to verify your identity against the Pi Platform API</li>
</ul>
<p>We never receive or store your Pi passphrase, private keys, wallet seed, or Pi account password.
We cannot access your Pi wallet.</p>

<h3>2.2 Provided by you</h3>
<ul>
  <li>Profile data: display name, bio, skills, portfolio links, avatar image, availability status</li>
  <li>Job postings, proposals and applications</li>
  <li>Messages and file attachments you exchange with other users</li>
  <li>Reviews and ratings you leave</li>
  <li>Dispute submissions and their supporting text</li>
</ul>

<h3>2.3 Generated by your use of the App</h3>
<ul>
  <li>Payment metadata: Pi payment identifiers, amounts, status, transaction IDs (public on the Pi blockchain)</li>
  <li>Escrow and milestone records, platform fee amounts</li>
  <li>Connects balance and purchase history</li>
  <li>Technical logs: IP address, timestamps, user agent, and error traces — retained for security and abuse prevention</li>
  <li>Push notification tokens, if you enable notifications</li>
</ul>

<h2>3. Legal Basis for Processing (GDPR Art. 6)</h2>
<ul>
  <li><strong>Contract performance</strong> — account, profile, jobs, messaging, escrow and payment records: processing is necessary to provide the service you requested.</li>
  <li><strong>Legitimate interests</strong> — security logging, fraud and abuse prevention, aggregated product analytics, enforcing our Terms.</li>
  <li><strong>Consent</strong> — push notifications and optional marketing communications. You may withdraw consent at any time.</li>
  <li><strong>Legal obligation</strong> — responding to lawful requests from competent authorities and retaining records where law requires it.</li>
</ul>

<h2>4. How We Use Your Information</h2>
<ul>
  <li>Authenticate you and display your public profile to other users</li>
  <li>Match freelancers with job opportunities and power search and filtering</li>
  <li>Facilitate Pi-denominated payments and escrow between clients and freelancers</li>
  <li>Calculate and collect the platform fee on completed transactions</li>
  <li>Deliver in-app and push notifications about activity relevant to you</li>
  <li>Investigate disputes, fraud, chargebacks and Terms violations</li>
  <li>Improve the App using aggregated, non-identifying statistics</li>
</ul>
<p>We do not use your data for automated decision-making that produces legal effects concerning you,
and we do not perform profiling for advertising purposes.</p>

<h2>5. What Other Users Can See</h2>
<p>Your username, avatar, bio, skills, portfolio, availability, ratings, reviews, completed job
count and public job postings are visible to other users of the App. Do not place sensitive
personal information — home address, identity documents, financial account details — in these
fields. Messages are visible to the participants of the conversation and, where a dispute is
raised, to the administrator resolving it.</p>

<h2>6. Data Sharing</h2>
<p>We do not sell, rent, or trade your personal data. We share it only with:</p>
<ul>
  <li><strong>Pi Network</strong> — to authenticate you and to submit, approve and complete Pi payments. Pi Network's own privacy policy governs that processing.</li>
  <li><strong>Infrastructure providers</strong> — our hosting and managed database provider, acting as processors under contract, solely to run the App.</li>
  <li><strong>Competent authorities</strong> — where we are legally compelled, or where disclosure is necessary to prevent imminent harm or investigate serious abuse.</li>
  <li><strong>A successor entity</strong> — if the App is transferred, merged, or acquired, subject to this policy continuing to apply.</li>
</ul>
<p>Pi blockchain transactions are inherently public. Amounts and wallet addresses recorded
on-chain are outside our control and cannot be deleted by us.</p>

<h2>7. International Transfers</h2>
<p>Our providers may process data outside your country of residence, including outside the
European Economic Area. Where that occurs we rely on the European Commission's Standard
Contractual Clauses or an adequacy decision as the transfer mechanism.</p>

<h2>8. Data Retention</h2>
<ul>
  <li>Account and profile data — for as long as your account is active</li>
  <li>Jobs, escrow, payment and fee records — up to 7 years after the transaction, to satisfy accounting, tax and dispute-defence obligations</li>
  <li>Messages — for the life of the account, or until deleted by both participants</li>
  <li>Security and audit logs — 12 months</li>
  <li>Backups — rolling, overwritten within 90 days</li>
</ul>
<p>After account deletion we retain only what law or the defence of legal claims requires,
in de-identified form where feasible.</p>

<h2>9. Your Rights (GDPR Art. 15–22)</h2>
<p>Subject to applicable law, you may request:</p>
<ul>
  <li><strong>Access</strong> — a copy of the personal data we hold about you</li>
  <li><strong>Rectification</strong> — correction of inaccurate data (most fields are self-editable in the App)</li>
  <li><strong>Erasure</strong> — deletion of your account and associated data</li>
  <li><strong>Restriction</strong> — that we pause processing while a dispute is resolved</li>
  <li><strong>Portability</strong> — your data in a structured, machine-readable format</li>
  <li><strong>Objection</strong> — to processing based on our legitimate interests</li>
  <li><strong>Withdrawal of consent</strong> — at any time, without affecting prior lawful processing</li>
</ul>
<p>Send requests to <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>. We respond within
30 days. We may ask you to verify control of your Pi account before acting on a request.
You also have the right to lodge a complaint with your national data protection authority.</p>

<h2>10. Security</h2>
<p>We apply industry-standard measures: TLS in transit, hashed session tokens, scoped
administrative access, rate limiting, input validation, and audit logging of privileged actions.
No system is perfectly secure. You are responsible for keeping your Pi Network credentials
confidential; anyone controlling your Pi account can access your Work Pro account.
If a breach affecting your rights occurs, we will notify affected users and the relevant
supervisory authority as required by law.</p>

<h2>11. Children</h2>
<p>Work Pro is not directed to and may not be used by anyone under 18. We do not knowingly
collect data from minors. If we learn that a minor has created an account, we will delete it.</p>

<h2>12. Cookies and Local Storage</h2>
<p>We use browser local storage for your session token, language preference, theme setting and
cached UI state. We do not use third-party advertising or cross-site tracking cookies.</p>

<h2>13. Changes to This Policy</h2>
<p>We may update this policy. Material changes will be announced in the App. Continued use
after the effective date constitutes acceptance. The "last updated" date above always reflects
the current version.</p>

<h2>14. Contact</h2>
<p>Privacy questions, rights requests, or complaints:
<a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>, or the contact option inside the App.</p>
`);
}

// ─── Terms of Service ─────────────────────────────────────────────────────────
function termsHtml(feePercent) {
  const fee = `${feePercent}%`;
  return shell('Terms of Service', `
<h1>Work Pro Terms of Service</h1>
<p><em class="upd">Last updated: ${LAST_UPDATED}</em></p>

<p>These Terms form a binding agreement between you and ${OPERATOR} ("we", "us"), the operator
of Work Pro ("the App"). Read them carefully — they limit our liability and affect your
legal rights.</p>

<div class="box">
<strong>Work Pro is a venue, not a party to your deals.</strong> We do not employ, supervise,
endorse, insure or vet users. We do not guarantee the quality, legality, safety or completion
of any job. Contracts are formed directly between client and freelancer. You transact at your
own risk.
</div>

<h2>1. Acceptance and Eligibility</h2>
<p>By using the App you accept these Terms. If you do not accept them, do not use the App.
You must be at least 18 years old and have a valid Pi Network account. You are solely
responsible for every action taken under your account and for keeping your Pi credentials
secure. You confirm you are not barred from using the App under any applicable sanctions
or export-control law.</p>

<h2>2. Nature of the Service</h2>
<p>Work Pro provides technology that lets clients post jobs and freelancers offer services,
with settlement in Pi via the Pi Network SDK. We are:</p>
<ul>
  <li><strong>Not an employer.</strong> Freelancers are independent contractors. Nothing here creates an employment, partnership, joint-venture or agency relationship with us.</li>
  <li><strong>Not a party</strong> to any client–freelancer contract.</li>
  <li><strong>Not a bank, money transmitter, payment institution, exchange or custodian.</strong> Pi movements are executed by the Pi Network protocol.</li>
  <li><strong>Not an escrow agent in the regulated sense.</strong> The escrow feature is an automated software convenience, not a licensed fiduciary service.</li>
  <li><strong>Not a provider of legal, tax, financial or investment advice.</strong></li>
</ul>

<h2>3. Payments, Fees and Escrow</h2>
<p>All payments are denominated in Pi. When a client funds a job, the amount is held by the
escrow mechanism until the client marks the job complete, a milestone is approved, or an
automatic release condition is met.</p>
<p>Work Pro charges a platform fee of <strong>${fee}</strong> on completed transactions.
This rate is displayed in the App before you commit to a transaction and may be changed
prospectively; the rate shown at the moment you transact is the rate that applies. The fee is
retained by us and is non-refundable once a transaction completes.</p>
<p>Applying to jobs consumes "connects", a prepaid in-app credit. Connects are a licence to
use a feature, not currency, not a security, not redeemable for Pi or fiat, and non-transferable.
Unused connects expire on account closure.</p>
<p>If no dispute is raised, escrowed funds release automatically to the freelancer 14 days after
work is submitted. Automatic release is a convenience and does not represent our judgement on
the merits of the work.</p>
<p><strong>You are solely responsible for all taxes</strong> arising from your use of the App,
including income, VAT, and any crypto-asset reporting obligation in your jurisdiction.
We do not withhold, remit, or report on your behalf.</p>

<h2>4. Cryptocurrency Risk</h2>
<p>Pi is a volatile digital asset. You acknowledge that:</p>
<ul>
  <li>Its value may fall, including to zero, at any time</li>
  <li>Blockchain transactions are irreversible — we cannot reverse, cancel or recover a confirmed transfer</li>
  <li>Network congestion, forks, protocol changes, wallet freezes, or Pi Network policy decisions may delay or permanently prevent transfers, and are outside our control</li>
  <li>Pi Network may not have enabled all payment capabilities in all regions or at all times</li>
  <li>Regulatory change may restrict or prohibit use of the App in your jurisdiction</li>
</ul>
<p>We are not liable for any loss arising from these risks.</p>

<h2>5. Disputes Between Users</h2>
<p>Disputes over work quality, scope, delivery or payment are between the client and the
freelancer. We may — but are never obliged to — review a disputed escrow and release or refund
funds. Any such decision is a good-faith administrative act to unblock the escrow mechanism.
It is not arbitration, not a legal determination, is final within the App, and creates no
liability for us. You waive any claim against us arising from a dispute decision.</p>

<h2>6. Prohibited Conduct</h2>
<p>You may not use the App to:</p>
<ul>
  <li>Post or solicit illegal work, or work that infringes third-party rights</li>
  <li>Post adult, violent, hateful, harassing, or discriminatory content</li>
  <li>Launder money, finance terrorism, or evade sanctions</li>
  <li>Circumvent the payment or fee system, or take transactions off-platform to avoid fees</li>
  <li>Manipulate reviews, ratings, or search ranking</li>
  <li>Operate multiple accounts to evade blocks, inflate reputation, or abuse promotions</li>
  <li>Scrape, reverse-engineer, overload, or probe the App or its API for vulnerabilities without written permission</li>
  <li>Impersonate any person, or misrepresent your skills, identity, or affiliation</li>
  <li>Upload malware or content containing another person's private data without their consent</li>
</ul>

<h2>7. Content and Licence</h2>
<p>Content you post remains yours. You grant us a worldwide, non-exclusive, royalty-free licence
to host, store, reproduce and display it for the purpose of operating and promoting the App.
You warrant that you hold the rights necessary to grant this licence.</p>
<p>Ownership of work product delivered under a job is governed by the agreement between client
and freelancer. We take no position on it and acquire no rights in it.</p>
<p>We may remove content or suspend accounts that we reasonably believe violate these Terms.
We have the right, but not the duty, to monitor content.</p>

<h2>8. Account Suspension and Termination</h2>
<p>We may suspend or terminate an account at any time, with or without notice, for breach of
these Terms, suspected fraud, legal requirement, or risk to other users or to the App. You may
close your account at any time. Funds held in an active escrow at termination will be resolved
under section 5. Sections 4, 9, 10, 11, 12 and 14 survive termination.</p>

<h2>9. Disclaimer of Warranties</h2>
<p>The App is provided <strong>"as is" and "as available"</strong>, without warranty of any kind,
express or implied, including merchantability, fitness for a particular purpose, title, accuracy,
and non-infringement. We do not warrant that the App will be uninterrupted, secure, error-free,
or that defects will be corrected. We do not warrant the identity, honesty, solvency, skills, or
work quality of any user. Where applicable law does not permit exclusion of a warranty, that
warranty is limited to the shortest period the law allows.</p>

<h2>10. Limitation of Liability</h2>
<p>To the maximum extent permitted by law, ${OPERATOR} and its operators will not be liable for:</p>
<ul>
  <li>Lost profits, lost earnings, lost data, lost opportunity, or loss of goodwill</li>
  <li>Indirect, incidental, special, consequential, exemplary or punitive damages</li>
  <li>Loss in the value of Pi, or any inability to transfer, convert or access Pi</li>
  <li>Acts or omissions of any user, including non-payment, non-delivery, or defective work</li>
  <li>Pi Network outages, protocol changes, wallet restrictions, or refusal to process a payment</li>
  <li>Unauthorised access to your account resulting from your own credential handling</li>
</ul>
<p><strong>Our total aggregate liability for all claims arising out of or relating to the App is
limited to the total platform fees you actually paid to us in the three months preceding the
event giving rise to the claim, or 10 Pi, whichever is greater.</strong></p>
<p>Some jurisdictions do not allow certain limitations; in those jurisdictions our liability is
limited to the minimum extent the law permits. Nothing here excludes liability for fraud,
wilful misconduct, or death or personal injury caused by negligence, where such exclusion is
prohibited by law.</p>

<h2>11. Indemnification</h2>
<p>You agree to indemnify, defend and hold harmless ${OPERATOR}, its operators and contributors
from any claim, demand, loss, liability, damage, fine, or expense (including reasonable legal
fees) arising out of or connected with: your use of the App; your content; your breach of these
Terms or of any law; your dealings, contracts, or disputes with another user; or any tax
liability of yours. We may assume exclusive defence of any such matter at your expense, and you
will cooperate with that defence.</p>

<h2>12. Force Majeure</h2>
<p>We are not liable for any failure or delay caused by events beyond our reasonable control,
including Pi Network downtime or policy change, hosting or database provider failure, internet
outage, cyberattack, act of government, sanctions, natural disaster, war, or epidemic.</p>

<h2>13. Changes to the Service and to These Terms</h2>
<p>We may modify, suspend, or discontinue any part of the App at any time. We may update these
Terms; material changes will be announced in the App. Continued use after the effective date
constitutes acceptance. If you do not accept the updated Terms, stop using the App.</p>

<h2>14. Governing Law and Disputes With Us</h2>
<p>These Terms are governed by the laws of ${JURISDICTION}, without regard to conflict-of-law
rules. Before filing any claim, you agree to first contact us at
<a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> and attempt good-faith resolution for
at least 60 days. Any unresolved dispute will be brought exclusively before the competent
courts of ${JURISDICTION}. Where you are a consumer resident in the European Union, this clause
does not deprive you of the protection of mandatory provisions of the law of your country of
residence, nor of your right to bring proceedings there.</p>
<p>Claims must be brought within one year after the cause of action arises, to the extent
permitted by law. You agree to bring claims only in your individual capacity, not as a
plaintiff or class member in any class or representative proceeding.</p>

<h2>15. General</h2>
<p>If any provision is held unenforceable, the remainder stays in force and the unenforceable
provision is reformed to the minimum extent necessary. Our failure to enforce a provision is
not a waiver. You may not assign these Terms; we may assign them in connection with a merger,
acquisition or transfer of the App. These Terms, together with the
<a href="/privacy">Privacy Policy</a>, are the entire agreement between you and us regarding
the App.</p>

<h2>16. Contact</h2>
<p>Questions about these Terms:
<a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>, or the contact option inside the App.</p>
`);
}

module.exports = { privacyHtml, termsHtml };
